//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpManagerWs.HukukWs {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HsResponseAuthenticate", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class HsResponseAuthenticate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        private int UserIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<UserId>k__BackingField", IsRequired=true)]
        public int UserIdk__BackingField {
            get {
                return this.UserIdk__BackingFieldField;
            }
            set {
                if ((this.UserIdk__BackingFieldField.Equals(value) != true)) {
                    this.UserIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("UserIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Statu", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    public enum Statu : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        fail = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMattersResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetMattersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private IpManagerWs.HukukWs.Proje[] Mattersk__BackingFieldField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Matters>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Proje[] Mattersk__BackingField {
            get {
                return this.Mattersk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Mattersk__BackingFieldField, value) != true)) {
                    this.Mattersk__BackingFieldField = value;
                    this.RaisePropertyChanged("Mattersk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proje", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class Proje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DevirKaydiVark__BackingFieldField;
        
        private string DevirTarihik__BackingFieldField;
        
        private int DevirTutariBirimiIDk__BackingFieldField;
        
        private double DevirTutarik__BackingFieldField;
        
        private double DevredenSurek__BackingFieldField;
        
        private int IDk__BackingFieldField;
        
        private string KapanmisProjek__BackingFieldField;
        
        private int MusteriIDk__BackingFieldField;
        
        private string Notlark__BackingFieldField;
        
        private double OzelDovizKuru1k__BackingFieldField;
        
        private double OzelDovizKuru2k__BackingFieldField;
        
        private string OzelDovizKuruVark__BackingFieldField;
        
        private string ProjeAdik__BackingFieldField;
        
        private string ProjeBaslangick__BackingFieldField;
        
        private string ProjeBitisk__BackingFieldField;
        
        private string ProjeKoduk__BackingFieldField;
        
        private int ProjeTipiIDk__BackingFieldField;
        
        private string VeriGirisDilik__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DevirKaydiVar>k__BackingField", IsRequired=true)]
        public string DevirKaydiVark__BackingField {
            get {
                return this.DevirKaydiVark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DevirKaydiVark__BackingFieldField, value) != true)) {
                    this.DevirKaydiVark__BackingFieldField = value;
                    this.RaisePropertyChanged("DevirKaydiVark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DevirTarihi>k__BackingField", IsRequired=true)]
        public string DevirTarihik__BackingField {
            get {
                return this.DevirTarihik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.DevirTarihik__BackingFieldField, value) != true)) {
                    this.DevirTarihik__BackingFieldField = value;
                    this.RaisePropertyChanged("DevirTarihik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DevirTutariBirimiID>k__BackingField", IsRequired=true)]
        public int DevirTutariBirimiIDk__BackingField {
            get {
                return this.DevirTutariBirimiIDk__BackingFieldField;
            }
            set {
                if ((this.DevirTutariBirimiIDk__BackingFieldField.Equals(value) != true)) {
                    this.DevirTutariBirimiIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("DevirTutariBirimiIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DevirTutari>k__BackingField", IsRequired=true)]
        public double DevirTutarik__BackingField {
            get {
                return this.DevirTutarik__BackingFieldField;
            }
            set {
                if ((this.DevirTutarik__BackingFieldField.Equals(value) != true)) {
                    this.DevirTutarik__BackingFieldField = value;
                    this.RaisePropertyChanged("DevirTutarik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<DevredenSure>k__BackingField", IsRequired=true)]
        public double DevredenSurek__BackingField {
            get {
                return this.DevredenSurek__BackingFieldField;
            }
            set {
                if ((this.DevredenSurek__BackingFieldField.Equals(value) != true)) {
                    this.DevredenSurek__BackingFieldField = value;
                    this.RaisePropertyChanged("DevredenSurek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<KapanmisProje>k__BackingField", IsRequired=true)]
        public string KapanmisProjek__BackingField {
            get {
                return this.KapanmisProjek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.KapanmisProjek__BackingFieldField, value) != true)) {
                    this.KapanmisProjek__BackingFieldField = value;
                    this.RaisePropertyChanged("KapanmisProjek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MusteriID>k__BackingField", IsRequired=true)]
        public int MusteriIDk__BackingField {
            get {
                return this.MusteriIDk__BackingFieldField;
            }
            set {
                if ((this.MusteriIDk__BackingFieldField.Equals(value) != true)) {
                    this.MusteriIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("MusteriIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Notlar>k__BackingField", IsRequired=true)]
        public string Notlark__BackingField {
            get {
                return this.Notlark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Notlark__BackingFieldField, value) != true)) {
                    this.Notlark__BackingFieldField = value;
                    this.RaisePropertyChanged("Notlark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OzelDovizKuru1>k__BackingField", IsRequired=true)]
        public double OzelDovizKuru1k__BackingField {
            get {
                return this.OzelDovizKuru1k__BackingFieldField;
            }
            set {
                if ((this.OzelDovizKuru1k__BackingFieldField.Equals(value) != true)) {
                    this.OzelDovizKuru1k__BackingFieldField = value;
                    this.RaisePropertyChanged("OzelDovizKuru1k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OzelDovizKuru2>k__BackingField", IsRequired=true)]
        public double OzelDovizKuru2k__BackingField {
            get {
                return this.OzelDovizKuru2k__BackingFieldField;
            }
            set {
                if ((this.OzelDovizKuru2k__BackingFieldField.Equals(value) != true)) {
                    this.OzelDovizKuru2k__BackingFieldField = value;
                    this.RaisePropertyChanged("OzelDovizKuru2k__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OzelDovizKuruVar>k__BackingField", IsRequired=true)]
        public string OzelDovizKuruVark__BackingField {
            get {
                return this.OzelDovizKuruVark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OzelDovizKuruVark__BackingFieldField, value) != true)) {
                    this.OzelDovizKuruVark__BackingFieldField = value;
                    this.RaisePropertyChanged("OzelDovizKuruVark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeAdi>k__BackingField", IsRequired=true)]
        public string ProjeAdik__BackingField {
            get {
                return this.ProjeAdik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeAdik__BackingFieldField, value) != true)) {
                    this.ProjeAdik__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeAdik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeBaslangic>k__BackingField", IsRequired=true)]
        public string ProjeBaslangick__BackingField {
            get {
                return this.ProjeBaslangick__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeBaslangick__BackingFieldField, value) != true)) {
                    this.ProjeBaslangick__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeBaslangick__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeBitis>k__BackingField", IsRequired=true)]
        public string ProjeBitisk__BackingField {
            get {
                return this.ProjeBitisk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeBitisk__BackingFieldField, value) != true)) {
                    this.ProjeBitisk__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeBitisk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeKodu>k__BackingField", IsRequired=true)]
        public string ProjeKoduk__BackingField {
            get {
                return this.ProjeKoduk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeKoduk__BackingFieldField, value) != true)) {
                    this.ProjeKoduk__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeKoduk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeTipiID>k__BackingField", IsRequired=true)]
        public int ProjeTipiIDk__BackingField {
            get {
                return this.ProjeTipiIDk__BackingFieldField;
            }
            set {
                if ((this.ProjeTipiIDk__BackingFieldField.Equals(value) != true)) {
                    this.ProjeTipiIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeTipiIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VeriGirisDili>k__BackingField", IsRequired=true)]
        public string VeriGirisDilik__BackingField {
            get {
                return this.VeriGirisDilik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.VeriGirisDilik__BackingFieldField, value) != true)) {
                    this.VeriGirisDilik__BackingFieldField = value;
                    this.RaisePropertyChanged("VeriGirisDilik__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetKullanicilarResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetKullanicilarResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IpManagerWs.HukukWs.Kullanicilar[] KullanicilarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IpManagerWs.HukukWs.Statu StatuField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IpManagerWs.HukukWs.Kullanicilar[] Kullanicilar {
            get {
                return this.KullanicilarField;
            }
            set {
                if ((object.ReferenceEquals(this.KullanicilarField, value) != true)) {
                    this.KullanicilarField = value;
                    this.RaisePropertyChanged("Kullanicilar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operation {
            get {
                return this.OperationField;
            }
            set {
                if ((object.ReferenceEquals(this.OperationField, value) != true)) {
                    this.OperationField = value;
                    this.RaisePropertyChanged("Operation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IpManagerWs.HukukWs.Statu Statu {
            get {
                return this.StatuField;
            }
            set {
                if ((this.StatuField.Equals(value) != true)) {
                    this.StatuField = value;
                    this.RaisePropertyChanged("Statu");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kullanicilar", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class Kullanicilar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Blokek__BackingFieldField;
        
        private string CalisanAdik__BackingFieldField;
        
        private string CalisanSoyadik__BackingFieldField;
        
        private string Emailk__BackingFieldField;
        
        private int GorevIDk__BackingFieldField;
        
        private int IDk__BackingFieldField;
        
        private string IseGirisTarihik__BackingFieldField;
        
        private string IstenCikisTarihik__BackingFieldField;
        
        private string KullaniciKoduk__BackingFieldField;
        
        private string SaatUcretlik__BackingFieldField;
        
        private string Sifrek__BackingFieldField;
        
        private string Sistemdek__BackingFieldField;
        
        private string YetkiDizisik__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Bloke>k__BackingField", IsRequired=true)]
        public string Blokek__BackingField {
            get {
                return this.Blokek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Blokek__BackingFieldField, value) != true)) {
                    this.Blokek__BackingFieldField = value;
                    this.RaisePropertyChanged("Blokek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CalisanAdi>k__BackingField", IsRequired=true)]
        public string CalisanAdik__BackingField {
            get {
                return this.CalisanAdik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CalisanAdik__BackingFieldField, value) != true)) {
                    this.CalisanAdik__BackingFieldField = value;
                    this.RaisePropertyChanged("CalisanAdik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CalisanSoyadi>k__BackingField", IsRequired=true)]
        public string CalisanSoyadik__BackingField {
            get {
                return this.CalisanSoyadik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.CalisanSoyadik__BackingFieldField, value) != true)) {
                    this.CalisanSoyadik__BackingFieldField = value;
                    this.RaisePropertyChanged("CalisanSoyadik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Email>k__BackingField", IsRequired=true)]
        public string Emailk__BackingField {
            get {
                return this.Emailk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Emailk__BackingFieldField, value) != true)) {
                    this.Emailk__BackingFieldField = value;
                    this.RaisePropertyChanged("Emailk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<GorevID>k__BackingField", IsRequired=true)]
        public int GorevIDk__BackingField {
            get {
                return this.GorevIDk__BackingFieldField;
            }
            set {
                if ((this.GorevIDk__BackingFieldField.Equals(value) != true)) {
                    this.GorevIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("GorevIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IseGirisTarihi>k__BackingField", IsRequired=true)]
        public string IseGirisTarihik__BackingField {
            get {
                return this.IseGirisTarihik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IseGirisTarihik__BackingFieldField, value) != true)) {
                    this.IseGirisTarihik__BackingFieldField = value;
                    this.RaisePropertyChanged("IseGirisTarihik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IstenCikisTarihi>k__BackingField", IsRequired=true)]
        public string IstenCikisTarihik__BackingField {
            get {
                return this.IstenCikisTarihik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IstenCikisTarihik__BackingFieldField, value) != true)) {
                    this.IstenCikisTarihik__BackingFieldField = value;
                    this.RaisePropertyChanged("IstenCikisTarihik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<KullaniciKodu>k__BackingField", IsRequired=true)]
        public string KullaniciKoduk__BackingField {
            get {
                return this.KullaniciKoduk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciKoduk__BackingFieldField, value) != true)) {
                    this.KullaniciKoduk__BackingFieldField = value;
                    this.RaisePropertyChanged("KullaniciKoduk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SaatUcretli>k__BackingField", IsRequired=true)]
        public string SaatUcretlik__BackingField {
            get {
                return this.SaatUcretlik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.SaatUcretlik__BackingFieldField, value) != true)) {
                    this.SaatUcretlik__BackingFieldField = value;
                    this.RaisePropertyChanged("SaatUcretlik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Sifre>k__BackingField", IsRequired=true)]
        public string Sifrek__BackingField {
            get {
                return this.Sifrek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Sifrek__BackingFieldField, value) != true)) {
                    this.Sifrek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sifrek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Sistemde>k__BackingField", IsRequired=true)]
        public string Sistemdek__BackingField {
            get {
                return this.Sistemdek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Sistemdek__BackingFieldField, value) != true)) {
                    this.Sistemdek__BackingFieldField = value;
                    this.RaisePropertyChanged("Sistemdek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<YetkiDizisi>k__BackingField", IsRequired=true)]
        public string YetkiDizisik__BackingField {
            get {
                return this.YetkiDizisik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiDizisik__BackingFieldField, value) != true)) {
                    this.YetkiDizisik__BackingFieldField = value;
                    this.RaisePropertyChanged("YetkiDizisik__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCalismalarResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetCalismalarResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private IpManagerWs.HukukWs.Calismalar[] Calismalark__BackingFieldField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Calismalar>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Calismalar[] Calismalark__BackingField {
            get {
                return this.Calismalark__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Calismalark__BackingFieldField, value) != true)) {
                    this.Calismalark__BackingFieldField = value;
                    this.RaisePropertyChanged("Calismalark__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Calismalar", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class Calismalar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Aciklamak__BackingFieldField;
        
        private string BaslangicSaatik__BackingFieldField;
        
        private string BitisSaatik__BackingFieldField;
        
        private double FaturalananSaatk__BackingFieldField;
        
        private double FaturalanmayanSaatk__BackingFieldField;
        
        private string FullNameCalisank__BackingFieldField;
        
        private int IDk__BackingFieldField;
        
        private int KullaniciIDk__BackingFieldField;
        
        private int OnayDurumuIDk__BackingFieldField;
        
        private string OnayDurumuk__BackingFieldField;
        
        private string ProjeAdik__BackingFieldField;
        
        private int ProjeIDk__BackingFieldField;
        
        private string ProjeKoduk__BackingFieldField;
        
        private double SilenenSaatk__BackingFieldField;
        
        private string Tarihk__BackingFieldField;
        
        private int Yetkik__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Aciklama>k__BackingField", IsRequired=true)]
        public string Aciklamak__BackingField {
            get {
                return this.Aciklamak__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Aciklamak__BackingFieldField, value) != true)) {
                    this.Aciklamak__BackingFieldField = value;
                    this.RaisePropertyChanged("Aciklamak__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BaslangicSaati>k__BackingField", IsRequired=true)]
        public string BaslangicSaatik__BackingField {
            get {
                return this.BaslangicSaatik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BaslangicSaatik__BackingFieldField, value) != true)) {
                    this.BaslangicSaatik__BackingFieldField = value;
                    this.RaisePropertyChanged("BaslangicSaatik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<BitisSaati>k__BackingField", IsRequired=true)]
        public string BitisSaatik__BackingField {
            get {
                return this.BitisSaatik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.BitisSaatik__BackingFieldField, value) != true)) {
                    this.BitisSaatik__BackingFieldField = value;
                    this.RaisePropertyChanged("BitisSaatik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FaturalananSaat>k__BackingField", IsRequired=true)]
        public double FaturalananSaatk__BackingField {
            get {
                return this.FaturalananSaatk__BackingFieldField;
            }
            set {
                if ((this.FaturalananSaatk__BackingFieldField.Equals(value) != true)) {
                    this.FaturalananSaatk__BackingFieldField = value;
                    this.RaisePropertyChanged("FaturalananSaatk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FaturalanmayanSaat>k__BackingField", IsRequired=true)]
        public double FaturalanmayanSaatk__BackingField {
            get {
                return this.FaturalanmayanSaatk__BackingFieldField;
            }
            set {
                if ((this.FaturalanmayanSaatk__BackingFieldField.Equals(value) != true)) {
                    this.FaturalanmayanSaatk__BackingFieldField = value;
                    this.RaisePropertyChanged("FaturalanmayanSaatk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<FullNameCalisan>k__BackingField", IsRequired=true)]
        public string FullNameCalisank__BackingField {
            get {
                return this.FullNameCalisank__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameCalisank__BackingFieldField, value) != true)) {
                    this.FullNameCalisank__BackingFieldField = value;
                    this.RaisePropertyChanged("FullNameCalisank__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public int IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((this.IDk__BackingFieldField.Equals(value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<KullaniciID>k__BackingField", IsRequired=true)]
        public int KullaniciIDk__BackingField {
            get {
                return this.KullaniciIDk__BackingFieldField;
            }
            set {
                if ((this.KullaniciIDk__BackingFieldField.Equals(value) != true)) {
                    this.KullaniciIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("KullaniciIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OnayDurumuID>k__BackingField", IsRequired=true)]
        public int OnayDurumuIDk__BackingField {
            get {
                return this.OnayDurumuIDk__BackingFieldField;
            }
            set {
                if ((this.OnayDurumuIDk__BackingFieldField.Equals(value) != true)) {
                    this.OnayDurumuIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("OnayDurumuIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OnayDurumu>k__BackingField", IsRequired=true)]
        public string OnayDurumuk__BackingField {
            get {
                return this.OnayDurumuk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OnayDurumuk__BackingFieldField, value) != true)) {
                    this.OnayDurumuk__BackingFieldField = value;
                    this.RaisePropertyChanged("OnayDurumuk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeAdi>k__BackingField", IsRequired=true)]
        public string ProjeAdik__BackingField {
            get {
                return this.ProjeAdik__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeAdik__BackingFieldField, value) != true)) {
                    this.ProjeAdik__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeAdik__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeID>k__BackingField", IsRequired=true)]
        public int ProjeIDk__BackingField {
            get {
                return this.ProjeIDk__BackingFieldField;
            }
            set {
                if ((this.ProjeIDk__BackingFieldField.Equals(value) != true)) {
                    this.ProjeIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ProjeKodu>k__BackingField", IsRequired=true)]
        public string ProjeKoduk__BackingField {
            get {
                return this.ProjeKoduk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjeKoduk__BackingFieldField, value) != true)) {
                    this.ProjeKoduk__BackingFieldField = value;
                    this.RaisePropertyChanged("ProjeKoduk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<SilenenSaat>k__BackingField", IsRequired=true)]
        public double SilenenSaatk__BackingField {
            get {
                return this.SilenenSaatk__BackingFieldField;
            }
            set {
                if ((this.SilenenSaatk__BackingFieldField.Equals(value) != true)) {
                    this.SilenenSaatk__BackingFieldField = value;
                    this.RaisePropertyChanged("SilenenSaatk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Tarih>k__BackingField", IsRequired=true)]
        public string Tarihk__BackingField {
            get {
                return this.Tarihk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Tarihk__BackingFieldField, value) != true)) {
                    this.Tarihk__BackingFieldField = value;
                    this.RaisePropertyChanged("Tarihk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Yetki>k__BackingField", IsRequired=true)]
        public int Yetkik__BackingField {
            get {
                return this.Yetkik__BackingFieldField;
            }
            set {
                if ((this.Yetkik__BackingFieldField.Equals(value) != true)) {
                    this.Yetkik__BackingFieldField = value;
                    this.RaisePropertyChanged("Yetkik__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCreateResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetCreateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetUpdateResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetUpdateResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDeleteResponse", Namespace="http://schemas.datacontract.org/2004/07/HukukWs.Model")]
    [System.SerializableAttribute()]
    public partial class GetDeleteResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string Messagek__BackingFieldField;
        
        private string Operationk__BackingFieldField;
        
        private IpManagerWs.HukukWs.Statu Statuk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Message>k__BackingField", IsRequired=true)]
        public string Messagek__BackingField {
            get {
                return this.Messagek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Messagek__BackingFieldField, value) != true)) {
                    this.Messagek__BackingFieldField = value;
                    this.RaisePropertyChanged("Messagek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Operation>k__BackingField", IsRequired=true)]
        public string Operationk__BackingField {
            get {
                return this.Operationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Operationk__BackingFieldField, value) != true)) {
                    this.Operationk__BackingFieldField = value;
                    this.RaisePropertyChanged("Operationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Statu>k__BackingField", IsRequired=true)]
        public IpManagerWs.HukukWs.Statu Statuk__BackingField {
            get {
                return this.Statuk__BackingFieldField;
            }
            set {
                if ((this.Statuk__BackingFieldField.Equals(value) != true)) {
                    this.Statuk__BackingFieldField = value;
                    this.RaisePropertyChanged("Statuk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HukukWs.IHsClient")]
    public interface IHsClient {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetSumOfTwoInts", ReplyAction="http://tempuri.org/IHsClient/GetSumOfTwoIntsResponse")]
        int GetSumOfTwoInts(int Operand1, int Operand2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetSumOfTwoInts", ReplyAction="http://tempuri.org/IHsClient/GetSumOfTwoIntsResponse")]
        System.Threading.Tasks.Task<int> GetSumOfTwoIntsAsync(int Operand1, int Operand2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/AuthenticateUser", ReplyAction="http://tempuri.org/IHsClient/AuthenticateUserResponse")]
        IpManagerWs.HukukWs.HsResponseAuthenticate AuthenticateUser(string dbname, string ip, int kullanicikodu, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/AuthenticateUser", ReplyAction="http://tempuri.org/IHsClient/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.HsResponseAuthenticate> AuthenticateUserAsync(string dbname, string ip, int kullanicikodu, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetProjeler", ReplyAction="http://tempuri.org/IHsClient/GetProjelerResponse")]
        IpManagerWs.HukukWs.GetMattersResponse GetProjeler(string dbname, string ip, int userid, int reporttype, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetProjeler", ReplyAction="http://tempuri.org/IHsClient/GetProjelerResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetMattersResponse> GetProjelerAsync(string dbname, string ip, int userid, int reporttype, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetKullanicilar", ReplyAction="http://tempuri.org/IHsClient/GetKullanicilarResponse")]
        IpManagerWs.HukukWs.GetKullanicilarResponse GetKullanicilar(string dbname, string ip, int userid, int reporttype, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetKullanicilar", ReplyAction="http://tempuri.org/IHsClient/GetKullanicilarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetKullanicilarResponse> GetKullanicilarAsync(string dbname, string ip, int userid, int reporttype, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetCalismalar", ReplyAction="http://tempuri.org/IHsClient/GetCalismalarResponse")]
        IpManagerWs.HukukWs.GetCalismalarResponse GetCalismalar(string dbname, string ip, string userid, string reporttype, string matterid, string kullaniciid, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/GetCalismalar", ReplyAction="http://tempuri.org/IHsClient/GetCalismalarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetCalismalarResponse> GetCalismalarAsync(string dbname, string ip, string userid, string reporttype, string matterid, string kullaniciid, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/CreateCalismalar", ReplyAction="http://tempuri.org/IHsClient/CreateCalismalarResponse")]
        IpManagerWs.HukukWs.GetCreateResponse CreateCalismalar(string dbname, string ip, string userid, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string kullaniciID, string faturalanan, string faturalanmayan, string silinen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/CreateCalismalar", ReplyAction="http://tempuri.org/IHsClient/CreateCalismalarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetCreateResponse> CreateCalismalarAsync(string dbname, string ip, string userid, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string kullaniciID, string faturalanan, string faturalanmayan, string silinen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/UpdateCalismalar", ReplyAction="http://tempuri.org/IHsClient/UpdateCalismalarResponse")]
        IpManagerWs.HukukWs.GetUpdateResponse UpdateCalismalar(string dbname, string ip, string id, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string faturalanan, string faturalanmayan, string silinen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/UpdateCalismalar", ReplyAction="http://tempuri.org/IHsClient/UpdateCalismalarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetUpdateResponse> UpdateCalismalarAsync(string dbname, string ip, string id, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string faturalanan, string faturalanmayan, string silinen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/DeleteCalismalar", ReplyAction="http://tempuri.org/IHsClient/DeleteCalismalarResponse")]
        IpManagerWs.HukukWs.GetDeleteResponse DeleteCalismalar(string dbname, string ip, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/DeleteCalismalar", ReplyAction="http://tempuri.org/IHsClient/DeleteCalismalarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetDeleteResponse> DeleteCalismalarAsync(string dbname, string ip, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/LoadKullanicilar", ReplyAction="http://tempuri.org/IHsClient/LoadKullanicilarResponse")]
        IpManagerWs.HukukWs.GetKullanicilarResponse LoadKullanicilar(string dbname, string ip, int userid, string selectedProjeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/LoadKullanicilar", ReplyAction="http://tempuri.org/IHsClient/LoadKullanicilarResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetKullanicilarResponse> LoadKullanicilarAsync(string dbname, string ip, int userid, string selectedProjeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/LoadProjeler", ReplyAction="http://tempuri.org/IHsClient/LoadProjelerResponse")]
        IpManagerWs.HukukWs.GetMattersResponse LoadProjeler(string dbname, string ip, int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHsClient/LoadProjeler", ReplyAction="http://tempuri.org/IHsClient/LoadProjelerResponse")]
        System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetMattersResponse> LoadProjelerAsync(string dbname, string ip, int userid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHsClientChannel : IpManagerWs.HukukWs.IHsClient, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HsClientClient : System.ServiceModel.ClientBase<IpManagerWs.HukukWs.IHsClient>, IpManagerWs.HukukWs.IHsClient {
        
        public HsClientClient() {
        }
        
        public HsClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HsClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HsClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HsClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetSumOfTwoInts(int Operand1, int Operand2) {
            return base.Channel.GetSumOfTwoInts(Operand1, Operand2);
        }
        
        public System.Threading.Tasks.Task<int> GetSumOfTwoIntsAsync(int Operand1, int Operand2) {
            return base.Channel.GetSumOfTwoIntsAsync(Operand1, Operand2);
        }
        
        public IpManagerWs.HukukWs.HsResponseAuthenticate AuthenticateUser(string dbname, string ip, int kullanicikodu, string password) {
            return base.Channel.AuthenticateUser(dbname, ip, kullanicikodu, password);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.HsResponseAuthenticate> AuthenticateUserAsync(string dbname, string ip, int kullanicikodu, string password) {
            return base.Channel.AuthenticateUserAsync(dbname, ip, kullanicikodu, password);
        }
        
        public IpManagerWs.HukukWs.GetMattersResponse GetProjeler(string dbname, string ip, int userid, int reporttype, string startdate, string enddate) {
            return base.Channel.GetProjeler(dbname, ip, userid, reporttype, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetMattersResponse> GetProjelerAsync(string dbname, string ip, int userid, int reporttype, string startdate, string enddate) {
            return base.Channel.GetProjelerAsync(dbname, ip, userid, reporttype, startdate, enddate);
        }
        
        public IpManagerWs.HukukWs.GetKullanicilarResponse GetKullanicilar(string dbname, string ip, int userid, int reporttype, string startdate, string enddate) {
            return base.Channel.GetKullanicilar(dbname, ip, userid, reporttype, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetKullanicilarResponse> GetKullanicilarAsync(string dbname, string ip, int userid, int reporttype, string startdate, string enddate) {
            return base.Channel.GetKullanicilarAsync(dbname, ip, userid, reporttype, startdate, enddate);
        }
        
        public IpManagerWs.HukukWs.GetCalismalarResponse GetCalismalar(string dbname, string ip, string userid, string reporttype, string matterid, string kullaniciid, string startdate, string enddate) {
            return base.Channel.GetCalismalar(dbname, ip, userid, reporttype, matterid, kullaniciid, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetCalismalarResponse> GetCalismalarAsync(string dbname, string ip, string userid, string reporttype, string matterid, string kullaniciid, string startdate, string enddate) {
            return base.Channel.GetCalismalarAsync(dbname, ip, userid, reporttype, matterid, kullaniciid, startdate, enddate);
        }
        
        public IpManagerWs.HukukWs.GetCreateResponse CreateCalismalar(string dbname, string ip, string userid, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string kullaniciID, string faturalanan, string faturalanmayan, string silinen) {
            return base.Channel.CreateCalismalar(dbname, ip, userid, tarih, baslangicSaati, bitisSaati, aciklama, projeID, kullaniciID, faturalanan, faturalanmayan, silinen);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetCreateResponse> CreateCalismalarAsync(string dbname, string ip, string userid, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string kullaniciID, string faturalanan, string faturalanmayan, string silinen) {
            return base.Channel.CreateCalismalarAsync(dbname, ip, userid, tarih, baslangicSaati, bitisSaati, aciklama, projeID, kullaniciID, faturalanan, faturalanmayan, silinen);
        }
        
        public IpManagerWs.HukukWs.GetUpdateResponse UpdateCalismalar(string dbname, string ip, string id, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string faturalanan, string faturalanmayan, string silinen) {
            return base.Channel.UpdateCalismalar(dbname, ip, id, tarih, baslangicSaati, bitisSaati, aciklama, projeID, faturalanan, faturalanmayan, silinen);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetUpdateResponse> UpdateCalismalarAsync(string dbname, string ip, string id, string tarih, string baslangicSaati, string bitisSaati, string aciklama, string projeID, string faturalanan, string faturalanmayan, string silinen) {
            return base.Channel.UpdateCalismalarAsync(dbname, ip, id, tarih, baslangicSaati, bitisSaati, aciklama, projeID, faturalanan, faturalanmayan, silinen);
        }
        
        public IpManagerWs.HukukWs.GetDeleteResponse DeleteCalismalar(string dbname, string ip, string id) {
            return base.Channel.DeleteCalismalar(dbname, ip, id);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetDeleteResponse> DeleteCalismalarAsync(string dbname, string ip, string id) {
            return base.Channel.DeleteCalismalarAsync(dbname, ip, id);
        }
        
        public IpManagerWs.HukukWs.GetKullanicilarResponse LoadKullanicilar(string dbname, string ip, int userid, string selectedProjeId) {
            return base.Channel.LoadKullanicilar(dbname, ip, userid, selectedProjeId);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetKullanicilarResponse> LoadKullanicilarAsync(string dbname, string ip, int userid, string selectedProjeId) {
            return base.Channel.LoadKullanicilarAsync(dbname, ip, userid, selectedProjeId);
        }
        
        public IpManagerWs.HukukWs.GetMattersResponse LoadProjeler(string dbname, string ip, int userid) {
            return base.Channel.LoadProjeler(dbname, ip, userid);
        }
        
        public System.Threading.Tasks.Task<IpManagerWs.HukukWs.GetMattersResponse> LoadProjelerAsync(string dbname, string ip, int userid) {
            return base.Channel.LoadProjelerAsync(dbname, ip, userid);
        }
    }
}
